default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5550129piyuelo
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  ##timeout: 5000

development:
  <<: *default
  database: hello_rails_react_development
  username: postgres

test:
  <<: *default
  database: hello_rails_react_test
  username: postgres

production:
  <<: *default
  database: hello_rails_react_production
  username: postgres
  password: <%= ENV["HELLO_RAILS_REACT_DATABASE_PASSWORD"] %>